const QUIPS = [
  "You're basically a saint. A trackable saint.",
  "Your data is out there living its best life.",
  "Somewhere, a retargeting algorithm just shed a tear of joy.",
  "You're the reason Karen in Marketing hit her Q3 targets.",
  "Plot twist: the cookies were tracking you anyway.",
  "Your browser history called. It said you're welcome.",
  "Congrats, you're now in 47 lookalike audiences.",
  "A/B tests everywhere just got more statistically significant.",
  "You just made a CDP very, very happy.",
  "Third-party cookies may be dying, but not on your watch.",
  "A marketing intern just got their first qualified lead. Thanks to you.",
  "Somewhere, a dashboard just turned green.",
  "Your privacy? A small price for better ad relevance.",
  "You're not a user. You're a first-party data goldmine.",
  "Attribution models everywhere just got a little less confused.",
  "A pixel just fired. And it was beautiful.",
  "You're single-handedly keeping the ad-tech ecosystem alive.",
  "That click was worth approximately $0.003 in CPM revenue.",
  "Your data profile just leveled up. Achievement unlocked.",
  "The algorithm sees you. The algorithm loves you.",
];
